language: node_js
node_js: node
cache:
  directories:
    - node_modules
script:
  - npm test
env:
  - CI=true

before_deploy:
  - npm install netlify-cli -g
  - npm run build

deploy:
  provider: script
  script: netlify deploy -s $bf406be1-f921-4c08-a66c-982b3a8973ce -t $c6a29dfd3fff74f3cae293045d0a782f0b147f8eddbac3b7fb647eaeb53e9dd7 -p ./build
  skip_cleanup: true
  on:
    branch: master